### ISSUE TITLE
Barricades for Castle Wars / Zombies

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#102]
This needs Ynneh's OSRS Pathing to be merged.

**Comment by tobywisener** [comment]
[Finished_Barricades_1_1_OSRS_can_burn_attack_kill_put_out_the_fire_when_on_fire_the_.zip](https://github.com/RSPSApp/elvarg-rsps/files/10187192/Finished_Barricades_1_1_OSRS_can_burn_attack_kill_put_out_the_fire_when_on_fire_the_.zip)

Attached finished work

**Comment by DrHenny** [comment]
finished
