### ISSUE TITLE
Clan chat messaging logs out player

### ISSUE THREAD

**Issue by syuil** [RSPSApp/elvarg-rsps#118]
Tested typing /hey /hey /hello etc. This was tested in my own clan chat.

Errors:
T1 - 32,0 - 65,81
T1 - 144,0 - 65,81
T1 - 168,0 - 65,81
T1 - 82,0 - 65,81
T1 - 93,0 - 65,81
T1 - 76,0 - 65,81

**Comment by DrHenny** [comment]
I'll take this one, should be very simple.

**Comment by DrHenny** [comment]
Fixed, pending merge.
