### ISSUE TITLE
Missing "close" button on Items Kept on Death Interface

### ISSUE THREAD

**Issue by syuil** [RSPSApp/elvarg-rsps#119]
![itemskeptondeath](https://user-images.githubusercontent.com/120953055/208715898-f5d997cd-5572-4b83-ae46-8666ea5f8893.png)

**Comment by DrHenny** [comment]
pending merg

**Comment by syuil** [comment]
I'm on the updated merge, did this get overwritten?

**Comment by DrHenny** [comment]
it might of, there was a branch for it.
