### ISSUE TITLE
Combat - if you try to click ditch or away you won't move

### ISSUE THREAD

**Issue by syuil** [RSPSApp/elvarg-rsps#127]
https://user-images.githubusercontent.com/120953055/209008046-c97b6312-1eda-4dc7-b4e8-9b7470366779.mp4

As you can see I'm not frozen trying to get away

Auto-retaliate was turned off as well

**Comment by syuil** [comment]
I'm on the merge right before the clanchat fix.

**Comment by syuil** [comment]
Attaching more to this issue, not related to combat but feels related to the same bug 

Clicking over things or doing a movement then going to try and do another thing like click NPC or bank or click the object you get a can't reach that message or a blank stare from the player and player won't do the action until I manually click again. 

https://user-images.githubusercontent.com/120953055/209012882-8052d932-9ace-4796-9142-2bc8640ef909.mp4

**Comment by DrHenny** [comment]
I'll take a look

**Comment by DrHenny** [comment]
pending merge

**Comment by syuil** [comment]
Can't follow NPC or Player now either.

**Comment by syuil** [comment]
This also only happens when in combat.

If player X is attacking player Y and player Y is not attacking back, player Y can run to ditch. Player X can't run to ditch if clicked on during combat.
