### ISSUE TITLE
Crash when ground items disappear

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#128]
Seems to be some kinda T2 packet mismatch error for ground item removal opcode.

![image](https://user-images.githubusercontent.com/13219416/209015952-4846a81a-3111-482c-8281-ee7b099d1e59.png)

**Comment by DrHenny** [comment]
That's not ground items. That is an arrayindex exception from removing objects.

**Comment by tobywisener** [comment]
> That's not ground items. That is an arrayindex exception from removing objects.

Just for future reference the T1/T2 opcodes mean nothing in this scenario as they were coming from leftover packet data from the end of packet 84
