### ISSUE TITLE
Small bugs with Pathing

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#142]
- [x] If you try to attack a player/npc on the other side of a tree/chair, "I can't reach that"
![image](https://user-images.githubusercontent.com/13219416/210134811-e69aacdd-a9e9-4fbe-8da6-c38dff775854.png)
(Note: This works on GroundItems)

- [x] Delay when interacting with NPCs, interaction happens a tick too late
OSRS: https://gyazo.com/9e3bec3ac3ddc66b53c946799d979ed1
Our server: https://i.gyazo.com/a2b06b2181bf7a3fdfca4b2685815a25.gif

- [x] Barrage player, run out of field of view, then switch to longrange attack mode and attack - you won't path towards the player and you won't attack
https://streamable.com/ledght

**Comment by DrHenny** [comment]
Fixed
