### ISSUE TITLE
WalkToActions no longer work since pathing upgrade

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#148]
The pathing upgrades have broken all WalkToTasks in the server. These should have been replaced when the pathing was upgraded but sadly they were just left broken.

We need to replace the player interaction related calls to:
```
player.getMovementQueue().walkToEntity(target, () -> ... );
```

And the ground item related calls to:
```
player.getMovementQueue().walkToGroundItem(pos, () -> ... );
```

- [x] Fix PlayerOptionPacketListener - option1
- [x] Fix PlayerOptionPacketListener - option 2
- [x] Fix PlayerOptionPacketListener - option 3
- [x] Fix SecondGroundItemOptionPacketListener
- [x] Fix UseItemPacketListener
- [x] Rip out WalkToTask, setWalkToTask etc and ensure they're not being used anywhere else

![image](https://user-images.githubusercontent.com/13219416/210189448-7bc60565-6151-4231-b447-f67857bc7723.png)

**Comment by DrHenny** [comment]
Finished/Pushed
