### ISSUE TITLE
[#210-RuneLite] Remaining issues

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#201]
- [x] Special bar is fooked
![image](https://user-images.githubusercontent.com/13219416/216758244-591bc509-f474-4f79-8440-fec39f09ed00.png)

- [x] Torso shoulders are weird
![image](https://user-images.githubusercontent.com/13219416/216758504-e93e88c0-87c1-43b8-9874-00a187fbbd69.png)

- [x] (Not urgent) Houses in canafis have missing walls
![image](https://user-images.githubusercontent.com/13219416/216759062-31b064f4-6c09-4ab4-92d2-dd2aef53c87c.png)

- [x] Minigame teleports are not clickable when resizable is dragged to a large size (screen res 1280x720)
![image](https://user-images.githubusercontent.com/13219416/216759202-d42ee504-29d0-437a-b0ab-2061da28d1a8.png)

**Comment by DrHenny** [comment]
torso issue has always been there even before runelite
