### ISSUE TITLE
Attacking player from under the same tile moves out 2 tiles instead of 1

### ISSUE THREAD

**Issue by Naton1** [RSPSApp/elvarg-rsps#262]
Here's a gif to show this first of all: https://i.imgur.com/KB9M9D3.mp4

It moves 2 tiles out from under the player to attack with range and magic (which is inconsistent with RS), and only 1 tile for melee (which is correct). Range/mage should be moving only 1 tile out as well.

Easy to reproduce, stand on the same tile as a player and then attack them with range/mage and it will move 2 tiles out instead of 1.

**Comment by DrHenny** [comment]
fixed, you wanted it like this right?
https://gyazo.com/1c7dc13db55d1acc58c108ea967f0d01
