### ISSUE TITLE
Implement 1:1 OSRS Pathfinding

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#71]
We need 1:1 OSRS pathing for walking, objects, pickup item, npc combat, pvp combat, following players, npc following players.

**Comment by tobywisener** [comment]
Ynneh currently working on this, approaching completion

**Comment by DrHenny** [comment]
+

**Comment by DrHenny** [comment]
Finished pending PR

**Comment by DrHenny** [comment]
finished, pushed another fix
