### ISSUE TITLE
Implement "Teleport To" / "Teleport to me" options on friends list

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#74]
So basically this would add two right click options for anyone on your friends list:
-"Teleport to"
-"Teleport to me"

-Needs to ask the end users permission for both scenarios, same thing as "[playername] sent you a trade request." 
But in blue. Click to accept. This will be a dark blue message. The messages will be
"[playerName] has requested to teleport to you. Click to accept."
"[playerName] has requested to teleport you to their location. Click to accept."
-Needs to have wildernessWarning set to true on the call to teleport so that if the person you're teleporting to is in the wilderness, you'll be warned first.
-If the player's private chat is set to Off, they wont see any requests to be teleported to or have someone teleport to them

**Comment by DrHenny** [comment]
I'll handle this.

**Comment by DrHenny** [comment]
finished

**Comment by tobywisener** [comment]
[-_Implemented__Teleport_To_____Teleport_to_me__options_on_friends_list.zip](https://github.com/RSPSApp/elvarg-rsps/files/10195722/-_Implemented__Teleport_To_____Teleport_to_me__options_on_friends_list.zip)

**Comment by DrHenny** [comment]
Any reason why this is still open and hasn't been merged yet?
