### ISSUE TITLE
Login via Discord (Oauth2)

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#77]
This task involves plugging in the following package and allowing authentication via discord.

-Implement oauth2 discord api using the linked package
-Client side: Replace New User button (left button) with "Login via Discord"
-Client should open browser and return with token to client, client should then send token and discord user ID, username to server 
-Add a field for discordUserId to Player, and add it to PlayerSave so it gets persisted
-(If needed) Add a discordToken to Player/PlayerSave

https://github.com/Mokulu/discord-oauth2-api

**Comment by shogunrsps** [comment]
Task started

**Comment by tobywisener** [comment]
Done. Needs integrated with Webclient
