### ISSUE TITLE
Ring of Morphing

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#91]
A wearable ring "Ring of Morphing" that can be used to transform into a given NPC.
-Item client side with first click option "Morph"
-Different NPCs will require higher Slayer levels (NPCs to be decided)
(Cat/Dog/Pig/Imp/Goblin/Cow/Skeleton/Zombie/Baby Dragon/Demon/Revanent/Count Draynor etc)
-Slayer points ##/99 will drain during morphing (just like prayer)
-Slayer points can be restored at an altar
-Restore and Super Restore will restore Slayer points at the same rate as Prayer
-When morphing, you will use the same combat style and strength as the NPC you have transformed into
-When morphing, your hitpoints remain the same
-When morphing, emotes on the menu will be disabled
-If you take off the ring, you will return to normal, including combat style

Future enhancements:
-Rings can degrade over time
-Rings can be crafted via the crafting skill
-Custom npc interaction when morphing

**Comment by DrHenny** [comment]
finished/pushed
