### ISSUE TITLE
2h Rotating Emote is off

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#92]
The emote for 2H rotating is off, check rune 2h sword as an example

![image](https://user-images.githubusercontent.com/13219416/204088882-599a8b06-5c84-4dd8-8ebc-cd8cef78d298.png)

**Comment by DrHenny** [comment]
working on it

**Comment by DrHenny** [comment]
index needs repacking with latest OSRS and I would assume the opcode values too would need adjusting

**Comment by DrHenny** [comment]
Uses 2 different types of 2h animations, the actual 2h 'swords' use the old 317 animations and the godswords use latest.
