### ISSUE TITLE
Switching between Fixed and Resizable is messed up

### ISSUE THREAD

**Issue by tobywisener** [RSPSApp/elvarg-rsps#97]
-Resizable 800x600 should be default
-Clicking on Fixed should change to fixed
-Clicking on Resizable should change to resizable

**Comment by reinismu** [comment]
> -Resizable 800x600 should be default
Only for desktops

**Comment by tobywisener** [comment]
> > -Resizable 800x600 should be default
> 
> Only for desktops

Yep agreed for the webclient, but the Java client only runs on desktops :D
